version: '3.2'
services:
    apache:
        image: granghetti/magento2-apache:v1.0
        ports:
            - '443:443'
            - '80:80'
            - '8080:8080'
        volumes:
            - ./:/var/www/html
            - ~/.composer:/var/www/.composer
        environment:
            XDEBUG_CONFIG: 'remote_host=172.17.0.1 remote_port=9000 remote_enable=1;'
            PHP_IDE_CONFIG: 'serverName=PHPSTORM'
        depends_on:
            - db
        links:
            - db
        networks:
            - magento2-network

    db:
        image: mariadb
        ports:
            - 3300:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=magento
            - MYSQL_USER=magento
            - MYSQL_PASSWORD=magento
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - magento2-network

    redis:
        image: redis
        ports:
            - 6379
        networks:
            - magento2-network

    redis-session:
        image: redis
        ports:
            - 6379
        networks:
            - magento2-network

    es01:
        image: elasticsearch:6.8.4
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata01:/usr/share/elasticsearch/data
            - .:/apps
        entrypoint: /apps/docker-entrypoint-es-plugins.sh
        ports:
            - 9200:9200
        networks:
            - magento2-network
    es02:
        image: elasticsearch:6.8.4
        container_name: es02
        environment:
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata02:/usr/share/elasticsearch/data
            - .:/apps
        entrypoint: /apps/docker-entrypoint-es-plugins.sh
        networks:
            - magento2-network
    es03:
        image: elasticsearch:6.8.4
        container_name: es03
        environment:
            - node.name=es03
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata03:/usr/share/elasticsearch/data
            - .:/apps
        entrypoint: /apps/docker-entrypoint-es-plugins.sh
        networks:
            - magento2-network

volumes:
    esdata01:
        driver: local
    esdata02:
        driver: local
    esdata03:
        driver: local

networks:
    magento2-network:
        driver: bridge
