version: '3.2'
services:
    apache:
        image: granghetti/magento2-apache
        ports:
            - "443:443"
            - "80:80"
            - "8080:8080"
        volumes:
            - ./:/var/www/html
            - ~/.composer:/var/www/.composer
        environment:
            XDEBUG_REMOTE_HOST: 172.17.0.1
        depends_on:
            - db
        links:
            - db
        networks:
            - magento2-network

    db:
        image: mariadb
        ports:
            - 3300:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=magento
            - MYSQL_USER=magento
            - MYSQL_PASSWORD=magento
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - magento2-network

    redis:
        image: redis
        ports:
            - 6379
        networks:
            - magento2-network

    redis-session:
        image: redis
        ports:
            - 6379
        networks:
            - magento2-network

    elasticsearch:
        image: elasticsearch:2.4
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearchdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - magento2-network

networks:
    magento2-network:
        driver: bridge
