version: '2'
services:
    apache:
        image: granghetti/magento2-apache
        # build: .
        ports:
            - '80:80' # web
            - '9001:9000' # xdebug
            # - "35729:35729" # live reload
        volumes:
            - ./:/var/www/html
            - ~/.composer:/var/www/.composer
            # - ~/.npm:/var/www/.npm
            # - ~/.nvm:/var/www/.nvm
        environment:
            XDEBUG_CONFIG: 'remote_host=localhost'
            PHP_IDE_CONFIG: 'serverName=Docker'
        depends_on:
            - db
        links:
            - db
        networks:
            - magento2-network

    db:
        image: mariadb
        ports:
            - 3300:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=magento
            - MYSQL_USER=magento
            - MYSQL_PASSWORD=magento
        volumes:
            - ./my.cnf:/etc/mysql/my.cnf
            - ./db:/var/lib/mysql
        networks:
            - magento2-network

    redis:
        image: redis
        ports:
            - 6379
        networks:
            - magento2-network

    redis-session:
        image: redis
        ports:
            - 6379
        networks:
            - magento2-network

networks:
    magento2-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
